// authentication action types
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION'
export const EMAIL_VERIFICATION_ERROR = 'EMAIL_VERIFICATION_ERROR'

// api querying
export const SEARCH_PAPERS = 'SEARCH_PAPERS'
export const SEARCH_PAPERS_SUCCESS = 'SEARCH_PAPERS_SUCCESS'
export const SEARCH_PAPERS_FAILURE = 'SEARCH_PAPERS_FAILURE'